tasks:
  - name: terraform
    before: |
      cd s3/cfn
      git clone https://github.com/hashicorp/terraform.git
      mv terraform /usr/local/bin/
  # random utilities
  - name: utils
    before: |
      sudo apt-get install tree
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
