#! /usr/bin/env bash

echo "== add user to group"

# check if the first argument is provided
if [ -z "$1" ]; then
    echo "No user name provided."
    exit 1
fi

# check if the second argument is provided
if [ -z "$1" ]; then
    echo "No group name provided."
    exit 1
fi

USER_NAME=$1
GROUP_NAME=$2

aws iam add-user-to-group \
    --user-name $USER_NAME \
    --group-name $GROUP_NAME
