#! /usr/bin/env bash

echo "== create bucket"

# check if the first argument is provided
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket --bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ca-central-1" \
--query Location \
-- output text
