#!/usr/bin/env bash

echo "== sync"

# Exit immediately if any command returns a non-zero status
set -e

# check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided."
    exit 1
fi

# check for file name prefix
if [ -z "$2" ]; then
    echo "No bucket name provided."
    exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# Define the output directory
OUTPUT_DIR="/tmp/s3-bash-scripts"

# remove the folder if it already exists
rm -r $OUTPUT_DIR

# Create the output folder
mkdir -p "$OUTPUT_DIR"

# Generate a random number between 5 and 10 for the number of files
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/$FILENAME_PREFIX_$i.txt"

    # Generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

# Display the created files
tree "$OUTPUT_DIR"

aws s3api sync $BUCKET_NAME $OUTPUT_DIR s3://$BUCKET_NAME/files
