#! /usr/bin/env bash

echo "== list mfa devices"

# check if the first argument is provided
if [ -z "$1" ]; then
    echo "No user name provided."
    exit 1
fi

USER_NAME=$1

aws iam list-mfa-devices \
    --user-name $USER_NAME
