#! /usr/bin/env bash

echo "== create user access keys"

# check if the first argument is provided
if [ -z "$1" ]; then
    echo "No user name provided."
    exit 1
fi

USER_NAME=$1

aws iam create-access-key --user-name $USER_NAME
