#!/usr/bin/env bash

echo "== deploy s3 bucket via Cloud Formation"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--region us-east-1 \
--stack-name $STACK_NAME
